// WCAG 2.2 success criteria and the eMAG 3.1 recommendations they map to.
// [name in English, name in Portuguese, level, eMAG recommendations]
export const SC = {
  "1.1.1": ["Non-text Content", "Conteúdo não textual", "A", ["3.6", "6.1"]],
  "1.2.1": ["Audio-only and Video-only", "Apenas áudio e apenas vídeo", "A", ["5.1", "5.2"]],
  "1.2.2": ["Captions (Prerecorded)", "Legendas (pré-gravadas)", "A", ["5.1"]],
  "1.2.3": ["Audio Description or Media Alternative", "Audiodescrição ou alternativa de mídia", "A", ["5.3"]],
  "1.2.5": ["Audio Description (Prerecorded)", "Audiodescrição (pré-gravada)", "AA", ["5.3"]],
  "1.3.1": ["Info and Relationships", "Informações e relações", "A", ["1.2", "1.3", "3.9", "3.10", "6.2", "6.7"]],
  "1.3.2": ["Meaningful Sequence", "Sequência com significado", "A", ["1.4"]],
  "1.3.4": ["Orientation", "Orientação", "AA", ["4.3"]],
  "1.3.5": ["Identify Input Purpose", "Identificar o propósito de entrada", "AA", ["6.5"]],
  "1.4.1": ["Use of Color", "Uso de cor", "A", ["4.2"]],
  "1.4.2": ["Audio Control", "Controle de áudio", "A", ["5.4"]],
  "1.4.3": ["Contrast (Minimum)", "Contraste (mínimo)", "AA", ["4.1"]],
  "1.4.4": ["Resize Text", "Redimensionar texto", "AA", ["4.3"]],
  "1.4.5": ["Images of Text", "Imagens de texto", "AA", ["3.6"]],
  "1.4.10": ["Reflow", "Refluxo", "AA", ["4.3"]],
  "1.4.11": ["Non-text Contrast", "Contraste não textual", "AA", ["4.1"]],
  "1.4.12": ["Text Spacing", "Espaçamento de texto", "AA", ["4.3"]],
  "1.4.13": ["Content on Hover or Focus", "Conteúdo em foco ou ao passar o mouse", "AA", ["2.7"]],
  "2.1.1": ["Keyboard", "Teclado", "A", ["2.1"]],
  "2.1.2": ["No Keyboard Trap", "Sem bloqueio do teclado", "A", ["2.1"]],
  "2.1.3": ["Keyboard (No Exception)", "Teclado (sem exceção)", "AAA", ["2.1"]],
  "2.2.1": ["Timing Adjustable", "Ajustável por tempo", "A", ["2.3", "2.4", "2.5"]],
  "2.2.2": ["Pause, Stop, Hide", "Pausar, parar, ocultar", "A", ["2.7", "5.5"]],
  "2.3.1": ["Three Flashes or Below Threshold", "Três flashes ou abaixo do limite", "A", ["2.6"]],
  "2.3.3": ["Animation from Interactions", "Animação a partir de interações", "AAA", ["5.5"]],
  "2.4.1": ["Bypass Blocks", "Ignorar blocos", "A", ["1.5"]],
  "2.4.2": ["Page Titled", "Página com título", "A", ["3.3"]],
  "2.4.3": ["Focus Order", "Ordem do foco", "A", ["1.4", "6.3"]],
  "2.4.4": ["Link Purpose (In Context)", "Finalidade do link (em contexto)", "A", ["3.5"]],
  "2.4.6": ["Headings and Labels", "Cabeçalhos e rótulos", "AA", ["1.3", "6.2"]],
  "2.4.7": ["Focus Visible", "Foco visível", "AA", ["4.4"]],
  "2.4.11": ["Focus Not Obscured (Minimum)", "Foco não obscurecido (mínimo)", "AA", ["4.4"]],
  "2.5.3": ["Label in Name", "Rótulo no nome", "A", ["6.2"]],
  "2.5.8": ["Target Size (Minimum)", "Tamanho do alvo (mínimo)", "AA", []],
  "3.1.1": ["Language of Page", "Idioma da página", "A", ["3.1"]],
  "3.1.2": ["Language of Parts", "Idioma de partes", "AA", ["3.2"]],
  "3.2.1": ["On Focus", "Em foco", "A", ["6.4"]],
  "3.2.2": ["On Input", "Em entrada", "A", ["6.4"]],
  "3.3.1": ["Error Identification", "Identificação de erro", "A", ["6.6"]],
  "3.3.2": ["Labels or Instructions", "Rótulos ou instruções", "A", ["6.2", "6.5"]],
  "3.3.3": ["Error Suggestion", "Sugestão de erro", "AA", ["6.6"]],
  "3.3.8": ["Accessible Authentication (Minimum)", "Autenticação acessível (mínima)", "AA", ["6.8"]],
  "4.1.2": ["Name, Role, Value", "Nome, função, valor", "A", ["2.2", "6.2"]],
  "4.1.3": ["Status Messages", "Mensagens de status", "AA", ["6.6"]],
};

// eMAG 3.1 recommendations, by number
export const EMAG = {
  "1.2": ["Organize the HTML in a logical, semantic way", "Organizar o código HTML de forma lógica e semântica"],
  "1.3": ["Use heading levels correctly", "Utilizar corretamente os níveis de cabeçalho"],
  "1.4": ["Logical reading and tab order", "Ordenar de forma lógica e intuitiva a leitura e tabulação"],
  "1.5": ["Anchors to jump to each content block", "Fornecer âncoras para ir direto a um bloco de conteúdo"],
  "1.8": ["Divide the information areas", "Dividir as áreas de informação"],
  "2.1": ["Every function available by keyboard", "Disponibilizar todas as funções da página via teclado"],
  "2.2": ["Scripted objects must be accessible", "Garantir que os objetos programáveis sejam acessíveis"],
  "2.3": ["No automatic periodic refresh", "Não criar páginas com atualização automática periódica"],
  "2.4": ["No automatic redirect", "Não utilizar redirecionamento automático de páginas"],
  "2.5": ["A way to change time limits", "Fornecer alternativa para modificar limite de tempo"],
  "2.6": ["No flashing content", "Não incluir situações com intermitência de tela"],
  "2.7": ["User control over timed changes", "Assegurar o controle do usuário sobre as alterações temporais do conteúdo"],
  "3.1": ["Identify the page language", "Identificar o idioma principal da página"],
  "3.2": ["Mark changes of language", "Informar mudança de idioma no conteúdo"],
  "3.3": ["A descriptive page title", "Oferecer um título descritivo e informativo à página"],
  "3.5": ["Clear, short link text", "Descrever links clara e sucintamente"],
  "3.6": ["Text alternatives for images", "Fornecer alternativa em texto para as imagens do sítio"],
  "3.9": ["Table titles and summaries", "Em tabelas, utilizar títulos e resumos de forma apropriada"],
  "3.10": ["Associate data cells with headers", "Associar células de dados às células de cabeçalho"],
  "4.1": ["Minimum contrast", "Oferecer contraste mínimo entre plano de fundo e primeiro plano"],
  "4.2": ["Not color alone", "Não utilizar apenas cor ou outras características sensoriais para diferenciar elementos"],
  "4.3": ["Resizing without losing function", "Permitir redimensionamento sem perda de funcionalidade"],
  "4.4": ["Visible focus", "Possibilitar que o elemento com foco seja visualmente evidente"],
  "5.1": ["Alternative for video", "Fornecer alternativa para vídeo"],
  "5.2": ["Alternative for audio", "Fornecer alternativa para áudio"],
  "5.3": ["Audio description for video", "Oferecer audiodescrição para vídeo pré-gravado"],
  "5.4": ["Audio control", "Fornecer controle de áudio para som"],
  "5.5": ["Animation control", "Fornecer controle de animação"],
  "6.1": ["Text for image buttons", "Fornecer alternativa em texto para os botões de imagem de formulários"],
  "6.2": ["Labels tied to their fields", "Associar etiquetas aos seus campos"],
  "6.3": ["Logical form order", "Estabelecer uma ordem lógica de navegação"],
  "6.4": ["No automatic change of context", "Não provocar automaticamente alteração no contexto"],
  "6.5": ["Instructions for data entry", "Fornecer instruções para entrada de dados"],
  "6.6": ["Identify and describe input errors", "Identificar e descrever erros de entrada de dados e confirmar o envio das informações"],
  "6.7": ["Group form fields", "Agrupar campos de formulário"],
  "6.8": ["Security without CAPTCHA", "Fornecer estratégias de segurança específicas ao invés de CAPTCHA"],
};

// rules whose eMAG match is narrower than their WCAG criterion
export const RULE_EMAG = {
  "image-alt": ["3.6"], "input-image-alt": ["6.1"], "role-img-alt": ["3.6"], "svg-img-alt": ["3.6"], "area-alt": ["3.6"], "object-alt": ["3.6"],
  label: ["6.2"], "select-name": ["6.2"], "label-title-only": ["6.2"], "form-field-multiple-labels": ["6.2"], "autocomplete-valid": ["6.5"],
  "link-name": ["3.5"], "link-in-text-block": ["4.2"], "button-name": ["2.2"],
  "heading-order": ["1.3"], "page-has-heading-one": ["1.3"], "empty-heading": ["1.3"],
  bypass: ["1.5"], "skip-link": ["1.5"], region: ["1.8"], "landmark-one-main": ["1.8"], "landmark-unique": ["1.8"], "landmark-no-duplicate-banner": ["1.8"], "landmark-no-duplicate-contentinfo": ["1.8"],
  "td-headers-attr": ["3.10"], "th-has-data-cells": ["3.10"], "td-has-header": ["3.10"], "table-duplicate-name": ["3.9"],
  "color-contrast": ["4.1"], "color-contrast-enhanced": ["4.1"], "meta-viewport": ["4.3"], "meta-viewport-large": ["4.3"], "meta-refresh": ["2.3", "2.4"],
  "document-title": ["3.3"], "html-has-lang": ["3.1"], "html-lang-valid": ["3.1"], "html-xml-lang-mismatch": ["3.1"], "valid-lang": ["3.2"],
  tabindex: ["1.4"], "scrollable-region-focusable": ["2.1"], "frame-title": ["3.3"], blink: ["2.6", "5.5"], marquee: ["5.5"], "video-caption": ["5.1"],
};
